services:

  server:
    image: ddrddrr2/house_prices:latest
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - django_static:/app/staticfiles
    expose:
      - "8000"
    networks:
      - main

  proxy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django_static:/app/staticfiles
    networks:
      - main

networks:
  main:

volumes:
  caddy_data:
  caddy_config:
  django_static: